language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - "./node_modules/.bin/bower install"
after_script:
  - "cat ./test/coverage/PhantomJS\ 1.9.7\ (Mac\ OS\ X)/lcov.info | ./node_modules/.bin/coveralls"
